spring:
 datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/classicmodels?useSSL=false&zeroDateTimeBehavior=convertToNull&autoReconnect=true
  username: root
  password: root
    

  